# TM-RugPull dataset initial analysis

## Data collection

In [1]:
# Loading data from .xlsx file

import pandas as pd
import numpy as np
import matplotlib.pyplot as pyplot

file = 'data/TM-RugPull.xlsx'

data = pd.read_excel(file)

# Remove a space in the end of some column names
data.columns = data.columns.str.strip()

print(data.shape)

pd.set_option('display.max_columns', None)

data.head(5)

(1000, 27)

,Project Title,MaxPrice (Quarter 1),MaxPrice (Quarter 2),MaxPrice (Quarter 3),MaxPrice (Quarter 4),Blockchain,the number of Transactions,Token concentration ratio per holder,Total Variance,Variance of holders with more than 1% tokens,Token balance,Sign,first deposits,Blockchain Type,Smart Contract (online),smart Contract (offline),website,x profile,class,project starting date,project end date,Google results for project title (first day),Google results for project title (project duration/2),Google results for project website (first day),Google results for project website (duration/2),Google results for project x profile (first days),Google results for project x profile (duration/2)
0,HyperVerse Token (HVT),7.650000e+00,1.500000e-01,9.100000e-06,8.000000e-07,BSC,623909,25752,9.537265e-03,4.929203e-02,166600000000100,HVT,44,POSA,sourse code,CODE,https://thehyperverse.net/index.html,https://twitter.com/HyperVerse6,scam,2022-01-27,2023-07-14,148,148,29,8,74,47
1,Fintoch,1.795000e-11,1.907000e-11,1.727000e-10,1.769000e-10,BSC,"1,492,842","147,791",2.487228e+03,4.503032e+07,34403.74594,BEP-20 TOKEN*,1,POSA,sourse code,CODE,https://web.archive.org/web/20230603123631/htt...,NaN,scam,2022-07-12,2023-06-19,820,167,4530,1590,48,4
2,Flare Token,1.955000e-03,5.519000e-04,4.158000e-04,2.838000e-04,BSC,"184,694",15173,8.901714e+14,6.695544e+17,10000000000,Flare,53,POSA,sourse code,CODE,https://pipeflare.io/,https://x.com/MetaFlareToken,scam,2021-10-24,2022-11-24,421,156,6,5,1710,1150
3,Safuu Protocol,2.070000e+02,2.110000e+02,7.000000e+01,2.400000e+01,BSC,"275,530",151979,2.457331e+10,8.139816e+14,61634066.59803,SAFUU,2,POSA,sourse code,CODE,https://safuu.com/,https://x.com/safuuxofficial,scam,2022-02-03,2022-08-13,327,323,0,0,5,4
4,SCT,2.986000e-01,1.659000e-01,1.831000e-01,1.552000e-01,BSC,8445,"6,126\n",4.252172e+06,1.410127e+05,"42,896,736.739367",SCT,52,POSA,sourse code,CODE,https://supercells.jp/en/,https://x.com/scttoken,scam,2023-02-27,2024-07-09,4990000,345000,6,3,1830,594

In [2]:
# Check the balance between classes in the whole dataset
# Source: https://note.nkmk.me/en/python-pandas-value-counts/#value_counts

class_counts = data['class'].value_counts()
class_percent = data['class'].value_counts(normalize=True) * 100

print("Counts:", class_counts.to_string(), "\nIn %:", class_percent.to_string())

Counts: class
scam      599
normal    401
In %: class
scam      59.9
normal    40.1

In [3]:
# Check general info about data

print("\nDataset information:")
data.info()

Dataset information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 27 columns):
 #   Column                                                 Non-Null Count  Dtype
---  ------                                                 --------------  -----
 0   Project Title                                          1000 non-null   object
 1   MaxPrice (Quarter 1)                                   1000 non-null   float64
 2   MaxPrice (Quarter 2)                                   1000 non-null   float64
 3   MaxPrice (Quarter 3)                                   1000 non-null   float64
 4   MaxPrice (Quarter 4)                                   1000 non-null   float64
 5   Blockchain                                             1000 non-null   object
 6   the number of Transactions                             1000 non-null   object
 7   Token concentration ratio per holder                   1000 non-null   object
 8   Total Variance                                         1000 non-null   float64
 9   Variance of holders with more than 1% tokens           1000 non-null   float64
 10  Token balance                                          1000 non-null   object
 11  Sign                                                   1000 non-null   object
 12  first deposits                                         1000 non-null   object
 13  Blockchain Type                                        1000 non-null   object
 14  Smart Contract (online)                                1000 non-null   object
 15  smart Contract (offline)                               1000 non-null   object
 16  website                                                999 non-null    object
 17  x profile                                              998 non-null    object
 18  class                                                  1000 non-null   object
 19  project starting date                                  1000 non-null   datetime64[ns]
 20  project end date                                       1000 non-null   datetime64[ns]
 21  Google results for project title (first day)           1000 non-null   int64
 22  Google results for project title (project duration/2)  1000 non-null   int64
 23  Google results for project website (first day)         1000 non-null   object
 24  Google results for project website (duration/2)        1000 non-null   object
 25  Google results for project x profile (first days)      1000 non-null   int64
 26  Google results for project x profile (duration/2)      1000 non-null   int64
dtypes: datetime64[ns](2), float64(6), int64(4), object(15)
memory usage: 211.1+ KB

In [4]:
# Delete columns that are not useful for further analysis

data.drop(columns=['Project Title', 'Sign', 'website', 'x profile', 'Smart Contract (online)', 'smart Contract (offline)', 'project starting date', 'project end date'], inplace=True)

# Check the transformation
data.head(10)

,MaxPrice (Quarter 1),MaxPrice (Quarter 2),MaxPrice (Quarter 3),MaxPrice (Quarter 4),Blockchain,the number of Transactions,Token concentration ratio per holder,Total Variance,Variance of holders with more than 1% tokens,Token balance,first deposits,Blockchain Type,class,Google results for project title (first day),Google results for project title (project duration/2),Google results for project website (first day),Google results for project website (duration/2),Google results for project x profile (first days),Google results for project x profile (duration/2)
0,7.650000e+00,1.500000e-01,9.100000e-06,8.000000e-07,BSC,623909,25752,9.537265e-03,4.929203e-02,166600000000100,44,POSA,scam,148,148,29,8,74,47
1,1.795000e-11,1.907000e-11,1.727000e-10,1.769000e-10,BSC,"1,492,842","147,791",2.487228e+03,4.503032e+07,34403.74594,1,POSA,scam,820,167,4530,1590,48,4
2,1.955000e-03,5.519000e-04,4.158000e-04,2.838000e-04,BSC,"184,694",15173,8.901714e+14,6.695544e+17,10000000000,53,POSA,scam,421,156,6,5,1710,1150
3,2.070000e+02,2.110000e+02,7.000000e+01,2.400000e+01,BSC,"275,530",151979,2.457331e+10,8.139816e+14,61634066.59803,2,POSA,scam,327,323,0,0,5,4
4,2.986000e-01,1.659000e-01,1.831000e-01,1.552000e-01,BSC,8445,"6,126\n",4.252172e+06,1.410127e+05,"42,896,736.739367",52,POSA,scam,4990000,345000,6,3,1830,594
5,3.260000e+00,6.900000e-01,4.500000e-01,3.900000e-01,BSC,"1,077,025",3744,4.248189e+12,1.291187e+15,249463052.264815,2000000000,POSA,scam,2920,568,1660,472,7,2
6,6.000000e+00,3.000000e+00,6.000000e+00,3.000000e+00,BSC,29680,2088,1.770589e+11,1.744026e+14,21000000,21000000,POSA,scam,2,2,0,0,319,137
7,1.400000e-05,9.700000e-06,9.200000e-06,6.000000e-07,BSC,146933,41487,2.617738e+10,6.783820e+13,100000000,10,POSA,scam,5330,3070,9,9,57300,40100
8,1.600000e+00,5.900000e-01,2.400000e-01,7.727200e+02,BSC,26854,1434,5.225230e+12,8.655448e+07,100000000,101000036,POSA,scam,42,9,1,1,10,6
9,7.100000e+00,3.360000e+00,2.990000e+00,1.810000e+00,BSC,18523,322,6.134499e+52,4.444444e+27,4444444444444439976202551054735245312,35186901407,POSA,scam,379,302,1,0,9070,4110

In [5]:
# Analysis of blockchain distribution in data

blockchain_distribution = data['Blockchain'].value_counts(normalize=True) * 100
print(blockchain_distribution.to_string())

Blockchain
ETH        63.3
BSC        32.1
POLYGON     2.4
ARBI        1.2
FANTOM      0.4
CRONO       0.2
BASE        0.2
FTM         0.1
SNOW        0.1

In [6]:
# Analyse scam rate per chain

scam_rate_per_chain = (
    data.groupby('Blockchain')['class']
        .apply(lambda s: (s == 'scam').mean())
        .sort_values(ascending=False)
)

scam_rate_percents = (scam_rate_per_chain * 100)

print(scam_rate_percents.to_string())

Blockchain
BASE       100.000000
CRONO      100.000000
FANTOM     100.000000
FTM        100.000000
BSC         75.077882
POLYGON     62.500000
ARBI        58.333333
ETH         51.658768
SNOW         0.000000

##### As far as FANTOM, CRONO, BASE and SNOW blockchains have very few samples (less than 10) and are biased (only scam tokens for BASE, CRONO and FANTOM and only normal samples for SNOW), these blockchains will be removed from the dataset to avoid overfitting.

In [ ]:
# Drop blockchains with number of samples less than 1%

min_samples = 1.0
chains_to_keep = blockchain_distribution[blockchain_distribution >= min_samples].index

print("Blockchains to keep:")
print(list(chains_to_keep))

print("\nDropped blockchains:")
print(blockchain_distribution[blockchain_distribution < min_samples].to_string())

data = data[data['Blockchain'].isin(chains_to_keep)].copy()

In [10]:
# Dataset after dropping blockchains with small number of samples

print(data.shape)
data.head(5)

(990, 19)

,MaxPrice (Quarter 1),MaxPrice (Quarter 2),MaxPrice (Quarter 3),MaxPrice (Quarter 4),Blockchain,the number of Transactions,Token concentration ratio per holder,Total Variance,Variance of holders with more than 1% tokens,Token balance,first deposits,Blockchain Type,class,Google results for project title (first day),Google results for project title (project duration/2),Google results for project website (first day),Google results for project website (duration/2),Google results for project x profile (first days),Google results for project x profile (duration/2)
0,7.650000e+00,1.500000e-01,9.100000e-06,8.000000e-07,BSC,623909,25752,9.537265e-03,4.929203e-02,166600000000100,44,POSA,scam,148,148,29,8,74,47
1,1.795000e-11,1.907000e-11,1.727000e-10,1.769000e-10,BSC,"1,492,842","147,791",2.487228e+03,4.503032e+07,34403.74594,1,POSA,scam,820,167,4530,1590,48,4
2,1.955000e-03,5.519000e-04,4.158000e-04,2.838000e-04,BSC,"184,694",15173,8.901714e+14,6.695544e+17,10000000000,53,POSA,scam,421,156,6,5,1710,1150
3,2.070000e+02,2.110000e+02,7.000000e+01,2.400000e+01,BSC,"275,530",151979,2.457331e+10,8.139816e+14,61634066.59803,2,POSA,scam,327,323,0,0,5,4
4,2.986000e-01,1.659000e-01,1.831000e-01,1.552000e-01,BSC,8445,"6,126\n",4.252172e+06,1.410127e+05,"42,896,736.739367",52,POSA,scam,4990000,345000,6,3,1830,594

In [9]:
# Display blockchain distribution after dropping blockchains with small number of samples

blockchain_distribution = data['Blockchain'].value_counts(normalize=True) * 100
print(blockchain_distribution.to_string())

Blockchain
ETH        63.939394
BSC        32.424242
POLYGON     2.424242
ARBI        1.212121

##### Create a test set and a validation test

In [ ]:
# Create a test set and a validation set from the raw data to avoid data leakage
# Validation set size is about 10,5% and test set size is about 24,5% from the whole data set
# TODO reference to AML tutorial

from sklearn.model_selection import train_test_split

# define size of data both for test and validatioin sets, define the seed for all subsequent experiments
test_and_val_size = 0.35
seed = 7

# Split the data first on train set and set for test and validation
train_set, test_and_val_set = train_test_split(data, test_size=test_and_val_size, random_state=seed, stratify=data['class'])

# Split the part for test and validation into test set and validation set
test_set, val_set = train_test_split(test_and_val_set, test_size=0.3, random_state=seed, stratify=test_and_val_set['class'])

# Output the shapes to verify the splits
print("Training set shape:", train_set.shape)
print("Test set shape:", test_set.shape)
print("Validation set shape:", val_set.shape)

# Create a list of sets to perform further feature engeneering on all subsets of data
data_sets = [train_set, test_set, val_set]

In [ ]:
# Verify that there is no overlap between sets, no data leak at this stage
print("Overlap between train and test:", np.intersect1d(train_set.index, test_set.index).size)
print("Overlap between train and validation:", np.intersect1d(train_set.index, val_set.index).size)
print("Overlap between test and validation:", np.intersect1d(test_set.index, val_set.index).size)

## Raw data analysis

#### Performed first on raw data to get overall idea of what the dataset contains
##### All further exploratory operations except checking general info should be done only on the train set to avoid data leakage.
##### Analysis of skew and correlation is performed only on numeric features first. Categorial features are initially analysed separately, then encoded during pre-processing.

In [ ]:
# Encode class label

from sklearn.preprocessing import LabelEncoder

for set in data_sets:
    le = LabelEncoder()
    set['class'] = set['class'].map({'normal': 0, 'scam': 1})

train_set

In [ ]:
# Check the data description

description = train_set.describe()
description

In [ ]:
# Check the balance between classes in the training set

class_counts_train = data['class'].value_counts()
class_percent_train = data['class'].value_counts(normalize=True) * 100

print("Counts:", class_counts_train.to_string(), "\nIn %:", class_percent_train.to_string())

In [ ]:
print(train_set.dtypes)

In [ ]:
# Transfer all data to numeric values

#TODO: reference from notes

# Columns with object datatype
cols_to_clean = [
    'the number of Transactions',
    'Token concentration ratio per holder',
    'Token balance',
    'first deposits',
    'Google results for project website (first day)',
    'Google results for project website (duration/2)'
]

# Do it for all sets
data_sets = [train_set, test_set, val_set]

for i, d_set in enumerate(data_sets):
    for col in cols_to_clean:
        data_sets[i][col] = pd.to_numeric(
            d_set[col].astype(str)
                   .str.replace('\xa0', '', regex=False)        # Remove non-breaking whitespaces
                   .str.replace(',', '', regex=False)           # Strip comas separating numeric values
                   .str.strip(),                                # Remove surrounding whitespaces
            errors='coerce'                                     # If cannot parse, put NaN
        )

train_set, test_set, val_set = data_sets

# Verify
print(train_set[cols_to_clean].dtypes)
print(train_set[cols_to_clean].isnull().sum())
print(train_set[cols_to_clean].describe())

In [ ]:
# Check for skew for numeric columns

numeric_cols = train_set.select_dtypes(include=['number']).columns
skew = train_set[numeric_cols].skew()

skew

### Visualisation

##### Based on CSM010-2024-APR, Topic 2, Lab.2.15. Analysing data

In [ ]:
# Histograms

train_set.hist(figsize=[30, 30])
pyplot.show()

In [ ]:
# Density plots

train_set.plot(kind='density', subplots=True, layout=(8,7), sharex=False, sharey=False, figsize=[30, 30])
pyplot.show()

In [ ]:
# Box and Whisker Plots

train_set.plot(kind='box', subplots=True, layout=(8,7), sharex=False, sharey=False,figsize=[30, 30])
pyplot.show()

##### Data is extremely skewed and there are extreme outliers, thus, data requires pre-processing.

In [ ]:
# Search for correlations of numeric features

correlations = train_set[numeric_cols].corr(method='pearson')

correlations

In [ ]:
# Correlation Matrix Plot

fig = pyplot.figure(figsize=[30, 30])
ax = fig.add_subplot(111)
cax = ax.matshow(correlations, vmin=-1, vmax=1)
fig.colorbar(cax)

ticks = np.arange(len(correlations.columns))

ax.set_xticks(ticks)
ax.set_yticks(ticks)

short_names = list(train_set[numeric_cols].columns)

ax.set_xticklabels(short_names)
ax.set_yticklabels(short_names)

pyplot.xticks(rotation=90)     # https://www.geeksforgeeks.org/how-to-rotate-x-axis-tick-label-text-in-matplotlib/?ysclid=lxdkiwmkrh456759424

pyplot.show()

In [ ]:
# Scatter plot Matrix
# TODO: make it more readable

pd.plotting.scatter_matrix(data, figsize=[20, 20])

pyplot.show()

##### Correlation matrix shows strong correlation (almost 1.0) between 'first deposits' and 'Q1'. Manual analysis reveal that 'first deposits' column is likely to be corrupted, since a lot of samples have the same float value here as in 'Q1', which does not make sense (there should be an integer).
##### There is also a strong correlation between price features (Q1, Q2, Q3 and Q4), thus, it is considered to drop three of them.

## Pre-processing of data

#### Based on results of data analysis on raw data

In [ ]:
# Remove 'first deposits' manually, since it seems to be corrupted (in majority cases it reproduces Q1 figures, which are prices, not deposits count)
# TODO: consider to replace 'first deposits' (number of initial liquidity deposit events)??

for set in data_sets:
    set.drop(columns=['first deposits'], inplace=True)

train_set

In [ ]:
# Replace strings in 'Blockchain', 'Blockchain Type', 'class' columns with numbers
# to make all features numeric for further analysis

#TODO: should I enforce specific values to each type of blockchain and its type or rely on LabelEncoder embedded?
#TODO: other ways to encode class values (see the book)
#TODO: reference to AML tutorial

from sklearn.preprocessing import LabelEncoder

for set in data_sets:
    le = LabelEncoder()
    set['Blockchain'] = le.fit_transform(set['Blockchain'])
    set['Blockchain Type'] = le.fit_transform(set['Blockchain Type'])

train_set

In [ ]:
# TODO: data require preparation and pre-processing (heavy skew, issues with 'first deposit' column (it seems that it is incorrect, duplicating Q1), outliers + a couple of missing values

# TODO: preparation and pre-processing